### ISSUE TITLE
关于adbyby的日志问题

### ISSUE THREAD

**Issue by liyiqqq** [kysdm/adbyby#1]
你好，想请教下路由上安装的adbyby如何输出全部日志
因为电视上的广告请求貌似屏蔽不掉，想查看下具体的url来编写针对的规则

1、我参照官方提供的两个配置，输出了blocked的日志
是否有其他参数值可以直接输出全部请求日志呢？
debug=1024
log-messages=1

2、或者是只能走路由的网关来打印日志呢？
如果用这种方法的话，请问配置为只输出某ip设备的请求记录的话 需要怎么配置呢？

请帮忙解答下，谢谢

**Comment by liyiqqq** [comment]
系统版本是：PandoraBox 17.01 2017-01-03-git-6c24a7a

**Comment by kysdm** [comment]
输出全部请求，adbyby是不行的
要用抓包工具才行
让所有流量通过抓包工具即可
